### ISSUE TITLE
TypeError: dilation2d_v2() got an unexpected keyword argument 'filter'

### ISSUE THREAD

**Issue by xuandong93** [dimitrisdais/crack_detection_CNN_masonry#1]
hi, i tried to train a model using your data set. but is facing this error. May i know if you know how to solve it ? thanks.

TypeError: dilation2d_v2() got an unexpected keyword argument 'filter'

**Comment by roguetechbee** [comment]
How this error got fixed
Plz share your tensorflow, keras versions

**Comment by xuandong93** [comment]
use
 output4D = tf.nn.dilation2d(img4D, filters=kernel, strides=(1,1,1,1),dilations=(1,1,1,1),  padding="SAME",data_format="NHWC")
 output4D = tf.nn.dilation2d(img4D, filter=kernel, strides=(1, 1, 1, 1), rates=(1, 1, 1, 1), padding="SAME")

**Comment by zluxYu** [comment]
I have the same problem，Can you share the solution？
